# -*- coding: utf-8 -*-
"""starsproject.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vmJq9C95Rnc4bwl8lOYxopsK7q1Tii92
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sb
from scipy.stats import pearsonr
data = pd.read_csv("/content/Stars.csv")
data = data.rename(columns={"L":"Luminance","R":"Radius"})
data = data.drop("Spectral_Class",axis=1)
data = data.drop("Type",axis=1)
data

t=data['Temperature'].values
plt.figure(figsize=(10,5),dpi=80)
plt.hist(t)
plt.title('Histogram of stars Temperture')
plt.xlabel('Temperture')
plt.ylabel('count')
plt.grid()
plt.show()
print('variance is',np.var(t),' and std is  ',np.std(t),' and average is ',np.mean(t),'and median is ',np.median(t),' so entropy > 0 because average > median ')

data = data.replace({"Blue":0, "Blue White":1, "Blue white":1, "Blue-White":1, "Blue-white":1})
data = data.replace({"Orange":2, "Orange-Red":3, "Pale yellow orange":4, "Red":5, "White":6})
data = data.replace({"White-Yellow":7, "Whitish":8, "Yellowish":9, "Yellowish White":10, "white":6})
data = data.replace({ "yellow-white":11, "yellowish":9})
rad = data["Radius"].values
plt.figure(figsize=(11,5),dpi=85)
plt.plot(x,rad)
plt.title('Radius of Stars')
plt.xlabel('type of stars')
plt.ylabel('R/R0')
plt.grid()
plt.show()
corr = data.corr()
hmap = sb.heatmap(corr,vmin = -1 , vmax = 1)
plt.title("correlation of stars")
plt.grid()
plt.show()

import matplotlib.pyplot as plt
x = [1,2,3,4]
def f(x):
  y = x
  return y
plt.plot(x,f(x))
plt.show()